### PR TITLE
Add1.28

### PR DESCRIPTION
**Pull request by zoelzw**
I added my solution to ex 1.28. Though I've double-checked and didn't find any calculation mistakes in my solution, 60% is low to show that all the power is consumed by the resistor. There're some online discussions about this question [https://math.stackexchange.com/questions/313508/circuit-analysis-series-rc-circuit-with-ac-supply](url) which looks very convincing but may require some good math intuitions. I will rethink this problem later. Or, please feel free to edit the solution.

### CODE REVIEW

**Comment by milesdai** [comment]
I haven't looked too carefully yet, but my guess is that this has to do with the low-pass-filter approximation you used -- I'm going to keep this PR open for a couple weeks to see if you or anyone else has time to come back to this, but I'll merge it in with an issue later if it's still outstanding. Even if the solution doesn't seem completely correct, I think it's still good for people to be able to see the work.

**Comment by jagjordi** [comment]
I don't think this is correct. The result should be that both (real) powers are identical since the capacitor does not consume real power. 

I have worked out by hand (not yet in latex) and I get this result as a result. (its a bit messy :sweat_smile: )
image
Can you take a look and see if you agree with my solution? If so I can typeset it :smiley:

**Comment by jagjordi** [comment]
See #29

**Comment by zoelzw** [comment]
Thanks, @milesdai and @jagjordi. I agree that I shouldn't have used the approximation. Then, my solution is the same as @jagjordi 's. Except for the denominators of both power expressions -- I think it should be 1+(𝜔𝑅𝐶)^2 instead of 1-(𝜔𝑅𝐶)^2. Could you please double-check the sign?

**Comment by jagjordi** [comment]
You are right @zoelzw it's with +.  In #29 I corrected have it correct but I forgot to comment it here.

**Comment by milesdai** [comment]
@zoelzw I did a force push to this branch to rebase it and merge it in to save you the trouble -- but you may want to delete the branch locally since it will be out of date now.

**Pull request merged**
