### PR TITLE
Solution to exercise 1.27

### PR DESCRIPTION
**Pull request by jagjordi**
this is how it looks after compiled

### CODE REVIEW

**Comment by milesdai** [comment]
Thanks for the contribution! Could you also push the built pdf to keep main.pdf up to date?

**Comment by jagjordi** [comment]
I added the PDF and made some improvements to the answer

**Comment by jagjordi** [comment]
This is how it looks 
image

**Comment by milesdai** [comment]
Looks good to me! Closes #27

**Pull request merged**
