### PR TITLE
Added 1.31,1.32,1.33

### PR DESCRIPTION
**Pull request by zoelzw**
I added my solutions to 1.31, 1.32, and 1.33. I'm still working on adding phasor diagrams to 1.32 and 1.33. As I mentioned in the issue, it took me too long to compile and see the plots. Would you mind taking a look? I'm new to git so apologize for the mess I made and thanks for correcting me :)

### CODE REVIEW

**Comment by milesdai** [comment]
Cool! I'm going to have you squash these last 5 commits into 1. Assuming you haven't made any changes to your repo since pushing these changes, can you run the following commands:
```shell
git reset --soft HEAD~5
git commit -m "Add 1.31-1.33"
git push --force
```
This will combine the last 5 commits into a single commit called Add 1.31-1.33. Sorry for the hassle -- a lot of this trouble is caused by my original decision to track main.pdf. I'm pretty close to deprecating this.

**Comment by milesdai** [comment]
With regards to the difficulty you're seeing in your workflow, take a look at this comment I made in #21 and the blog post I linked there for how to effectively use a rebase workflow: https://github.com/milesdai/TAoE3Solutions/pull/21#issuecomment-1045833649

**Comment by jensenr30** [comment]
@zoelzw 
Nice work on 1.31, 1.32, and 1.33!
Echoing milesdai's formatting guideline: exercise 1.33 should not be separated into a part (a) and a part (b) because the original Exercise statement does not include two separate parts.  So your solution to 1.33 should have no `begin{enumeration}` and also no `\item`s.

Keep up the great work.
Jensen

**Comment by milesdai** [comment]
@zoelzw Is there a reason you closed this issue?

**Comment by zoelzw** [comment]
Hi Miles,

Sorry about the confusion. I wanted to squash the commits into one but
messed it up. I'm still trying to figure out what to do next.

The "add 1.31" branch on my GitHub contains the commits that I want to keep
(added 1.31 - 1.33). I accidentally deleted the branch locally. My local
master branch is up to date with the origin/master branch but is behind
your master branch. Do you have any recommendations? I'm slowly practicing
git and would love to solve this asap so that I can keep working on the
exercises in parallel.

Thanks!

Zoe,

**Pull request closed without merging**
